title: Be Framework
description: Ontological programming framework where objects become what they are meant to be
baseurl: ""
url: "https://koriym.github.io/be-framework"

markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Minimal, clean navigation
header_pages:
  - manual/README.md
  - manual/convention/README.md

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - "*.sh"