title: Be Framework
description: Ontological programming framework where objects become what they are meant to be
baseurl: "/be-framework"
url: "https://koriym.github.io"

markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Minimal, clean navigation
header_pages:
  - manual/index.md
  - manual/convention/index.md

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - "*.sh"